[package]
name = "altv-core"
version = "0.1.0"
authors = ["Dimaa <personal@dimaa.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shrev = "1.1.1"
specs = "0.16.1"
